### PR TITLE
Aa task css

### PR DESCRIPTION
**Pull request by AliAbdulle**
# Description
Added style css my buttons and dom display fields. please check my output dom if they were standing side by side. Also, button styling color 
1. add button green
2. edit button blue
3. delete button red

Applies to issue # (2)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing Instructions

git fetch --all
go to src/lib
run grunt

past main.js following code:

import taskForm from "./task/taskForm.js"
import tasksDomBuilder from "./task/tasksDomBuilder.js";
import taskEventHandler from "./task/taskEventHandler.js";

taskForm.taskFormSection()
tasksDomBuilder.listAllTask()

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by anneraev — CHANGES_REQUESTED** [review]
The buttons are very tiny, so the text is actually larger than the buttons. Also, take a look at the CSS for buttons because its not set up right. Also, could you remove most of the sizing from the global buttons (or at least make them bigger). I can overwrite that for the other buttons, however I don't want to spend time doing that right now because we still have so much to worry about aside from CSS.

**Review by anneraev — DISMISSED** [review]
On second thought, it's functional. It's a good start for the design. I want you to drive on putting this page together, so we can fix while we're doing that. You're much better at CSS than I am and I have something to learn from you, so you should really drive on this part and I think you've got a good start here. We should do the whole page at once. Really good start! :)

**Review by Theskiman — DISMISSED** [review]
Css looks good for tasks

**Review by anneraev — DISMISSED** [review]
Looks good. I like the look of your boxes. :)

**Review by Theskiman — APPROVED** [review]
CSS looks good.

**Review by anneraev — APPROVED** [review]
Approved again!

**Pull request merged**
