### PR TITLE
Ba tesk nutshell

### PR DESCRIPTION
**Pull request by AliAbdulle**
# Description

Please check my form i created three input field that except name, description, and date stored date to database. 
Note: I would leave my call function into main.js thanks
Applies to issue # (issue number)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing Instructions

Please describe the tests required to verify your changes. Provide instructions so PR Tester can check functionality. Please also list any relevant details for your tests

# Checklist:

- [X ] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ X] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by Theskiman — APPROVED** [review]
Form works and saves to database.

**Review by Theskiman — DISMISSED** [review]
Form works and saves to database.

**Review by anneraev — DISMISSED** [review]
Looks good! I would reccommend using the dedicated date input form that Michael is teaching you, but other that it works. Great job, Ali! :)

Also, be sure to fix that merge conflict. It's main. Just pull down master into your branch and merge the changes. I'll be happy to help if you need me to.

**Review by anneraev — APPROVED** [review]
It seems to be posting to the dom, and you took care of the merge conflict. Great job, Ali! You're doing good.

**Review by myankura — APPROVED** [review]
Your save button is saving data to the API and pushing to the DOM, but, you will need to make it able to clear the element and refresh data so that there are no duplicates.  You're on the right track! 👍

**Pull request merged**
